plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0-M1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.aml'
version = '0.0.1-SNAPSHOT'
description = 'transactionIngestService'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.kafka:kafka-streams'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('bootBuildImage') {
    runImage = 'paketobuildpacks/ubuntu-noble-run:latest'
}

tasks.named('test') {
    useJUnitPlatform()
}
