spring.application.name=transactionIngestService
spring.kafka.bootstrap-servers=localhost:9092
kafka.topics.transactions.raw=transactions-raw
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.datasource.url=jdbc:postgresql://localhost:5432/ingestServiceDB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:classpath:application-local.properties
